name: "Matt Clements"
description: "Web Developer from Milton Keynes"
#url: "http://localhost:4000"

url: "http://mattclements.co.uk"

#auto: true
#server: true
exclude: ['README.md', 'sass/']

paginate: 7

permalink: pretty
pygments: true